# Generated by Django 3.2.9 on 2024-06-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='products.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions_depth',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions_height',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions_width',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
